apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
type: Opaque
stringData:
  REDIS_URL: redis://:redis123@redis:6379
  SERVICE_API_KEY: tm_key_fa2e4ecfbf8152e3eaebc7b04e72e5bbbc58607a3e24168162ae65e09c2175d4
  AWS_ACCESS_KEY_ID: fake
  AWS_SECRET_ACCESS_KEY: fake
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://elasticmq:9324
  AWS_SQS_URL: http://elasticmq:9324/000000000000/evaluation-queue
