apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: development
type: Opaque
stringData:
  REDIS_URL: "redis://:redis123@redis:6379"
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/auth_db"
  MASTER_KEY: "admin-secreto-123"
  SERVICE_API_KEY: "tm_key_9b086e1d95550a4b43cd8690df886056d123dc8e6c067a0c6c7bcefc9013fe6b"
  AWS_ACCESS_KEY_ID: "fake"
  AWS_SECRET_ACCESS_KEY: "fake"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT: "http://ministack:4566"
  AWS_SQS_URL: "http://ministack:4566/000000000000/evaluation-queue"

